### ISSUE TITLE
Use parallelization

### ISSUE THREAD

**Issue by LecrisUT** [lukka/run-cmake#129]
The action should set the following environment variables, especially when presets are used:
```yaml
CMAKE_BUILD_PARALLEL_LEVEL: $(nproc)
CTEST_PARALLEL_LEVEL: $(nproc)
```
These could be controlled by:
```yaml
parallel: auto | none
build_parallel: ${parallel:-auto | none}
test_parallel: ${parallel:-auto | none}
```
