### ISSUE TITLE
Multiline cmakeAppendedArgs Values?

### ISSUE THREAD

**Issue by kwhat** [lukka/run-cmake#20]
Is it possible to spread `cmakeAppendedArgs` across multiple lines?

For example, the `cmakeAppendedArgs` is getting quite long.  Is there any way to break these apart?
```
      - name: Compile
        uses: lukka/run-cmake@v2.4
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeAppendedArgs: '-DCMAKE_C_FLAGS=""-march=k8 -mtune=generic -O2 -g -fomit-frame-pointer -fno-stack-protector -pipe" -DCMAKE_VERBOSE_MAKEFILE=true -DENABLE_STATIC=ON'
          buildDirectory: ${{ github.workspace }}/build/
```

Thanks
