### ISSUE TITLE
CMAKE not recognizing BuildType argument

### ISSUE THREAD

**Issue by rickomax** [lukka/run-cmake#4]
Hi!

I'm passing `-DCMAKE_BUILD_TYPE=Release` argument to the `cmakeAppendedArgs` action, but CMAKE doesn't recognize it. Is there any extra step needed to make it work?

**Comment by lukka** [comment]
@rickomax thanks for the report!
I think that the problem is the following: 
 - setting `cmakeListsOrSettingsJson` to `CMakeListsTxtBasic`;
 - setting any value for `cmakeAppendedArgs`, that is this mode is ignored, as documented:

```
 cmakeAppendedArgs:
    default: ""
    required: false
    description: "Provides a mean to provide all the CMake arguments. 
This is required when using CMakeLists.txt in Advanced mode. 
For CMakeSettings.json, the arguments are already inferred, but you can append
 your arguments providing them here.  Used by CMakeListsTxtAdvanced and CMakeSettingsJson modes."
```


I think the action should be improved and warn about any argument that is being currently set by the user but disregarded at the same time during execution.

**Comment by iovw** [comment]
I have the same problem, by using ` cmakeBuildType: Release` and `cmakeGenerator: VS16Win64`
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_BUILD_TYPE
```

**Comment by iovw** [comment]
I see [this](https://stackoverflow.com/questions/24460486/cmake-build-type-is-not-being-used-in-cmakelists-txt)

In the build pass, it also need passing a args `--config Release` with Visual Studio or Xcode.

**Comment by lukka** [comment]
@iovw thanks for the report! 
The problem is that run-cmake action is passing `CMAKE_BUILD_TYPE` when it is not necessary (for example, when the `Visual Studio generator` is being used), and CMake is then correctly reporting the warning about 'unused input'.

In order to not show the warning, you could either use CMake's Ninja generator. Also take in consideration that with using `cmakeListsOrSettingsJson : CMakeListsTxtAdvanced` you can create your command line for CMake using `cmakeAppendedArgs`

I believe the original poster has a slightly different problem, we will find out.

**Comment by rickomax** [comment]
This is my full command, which still doesn't work:
```
steps:
      - uses: actions/checkout@v2
      - uses: lukka/run-cmake@v0
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: false
          buildDirectory: '${{ runner.workspace }}/build/win64'
          cmakeAppendedArgs: '-G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=MinSizeRel -DASSIMP_BUILD_TESTS=OFF -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_NO_EXPORT=ON -DBUILD_SHARED_LIBS=ON -DUSE_AES=OFF -DZIP_64=ON -DSKIP_INSTALL_ALL=ON -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=ON -DSKIP_MSVC_UPDATE=ON -DCMAKE_CONFIGURATION_TYPES="MinSizeRel" --config MinSizeRel'      
```
