### ISSUE TITLE
How to provide `-D` arguments/defined vars? - `cmakeAppendedArgs: '-DVAR=1'` fails

### ISSUE THREAD

**Issue by SamuelMarks** [lukka/run-cmake#48]
Attempt:
```yml
with:
    cmakeGenerator: 'Ninja'
    cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
    cmakeAppendedArgs: '-DSTANDALONE_MODE=1'
```

https://github.com/SamuelMarks/premiere-pro-cmake-plugin/actions/runs/1040412150

Or does it not work in `CMakeListsTxtBasic`?
