### ISSUE TITLE
Semicolons in cmakeAppendedArgs

### ISSUE THREAD

**Issue by garethsb** [lukka/run-cmake#55]
The following does not work as I expected on Linux and macOS runners.

```
- name: test
  uses: lukka/run-cmake@v3.4
  with:
    cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
    ...
    cmakeAppendedArgs: '-GNinja -DFOO_BAR="foo;bar"'
```

It appears `argStringToArray` strips off double quotes, and I suspect the `cmake` command line ends up with an unquoted semicolon which acts as a command terminator and therefore in the log:

```
  CMake Warning:
    No source or binary directory provided.  Both will be assumed to be the
    same as the current working directory, but note that this warning will
    become a fatal error in future CMake releases.
```

The hint was that on Windows runners this works fine, because `;` isn't special.

I've worked around it for now by:

```
    cmakeAppendedArgs: '-GNinja "-DFOO_BAR=\"foo;bar\""'
```

But that doesn't feel right to me?
