### ISSUE TITLE
How do I just do `vcpkg install packages && cmake -DCMAKE_TOOLCHAIN_FILE=%vcpkg%\scripts\buildsystems\vcpkg.cmake"`?

### ISSUE THREAD

**Issue by SamuelMarks** [lukka/run-cmake#60]
Maybe I'm overcomplicating things, but I want to do:
```yml
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          git clone --depth=1 https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install libarchive
      - name: build
        run: |
          md cmake-build-debug
          cd cmake-build-debug
          cmake .. -DCMAKE_TOOLCHAIN_FILE="..\vcpkg\scripts\buildsystems\vcpkg.cmake"
          cmake --build .
        shell: cmd
      - name: test
        run: ctest .
        working-directory: cmake-build-debug
```

Except I want to cache everything vcpkg related. Happy to pin https://github.com/Microsoft/vcpkg to a specific commit hash.

**How do I do this with run-cmake, without introducing vcpkg as a submodule?**

(also preferably without a `vcpkg.json`)

Thanks,

PS: I tried one the examples with submodule ❌'d on https://github.com/marketplace/actions/run-vcpkg#samples… but it still required a submodule
