### ISSUE TITLE
Permit additional cmake variables to be set in addition to the preset

### ISSUE THREAD

**Issue by justusranvier** [lukka/run-cmake#92]
Presets are a good feature but it can be impractical to write a CMakePresets.json that contains every necessary variable, particularly if you have a cmake variable whose value needs to match a matrix variable.

The only way to use this action in that case is to hard code the matrix from the action into CMakePresets.json which means now you have two files which must be kept in sync with each other or else your action will break.

cmake itself allows additional variables to be set on the command line even when a preset is specified.

**Comment by lukka** [comment]
@justusranvier seems reasonable to have this feature in order to avoid having to keep in sync two files. What would be exactly needed? How would you like to invoke the action?

**Comment by lukka** [comment]
@justusranvier looking forward to hear what would be useful for your scenario.

Would this be ok:

```
uses: run-cmake@v10
with:
    configurePreset: name
    buildPreset: name
    buildPresetAdditionalArguments: "-DName=Value -DName2=Value2"
```

then the action would run the following when building:

`cmake --build --preset name -DName=Value -DName2=Value2`

where the provided additional argument as used **as is** without any processing executed by the action.

Similarly for `configurePreset` and `testPreset`.
