### ISSUE TITLE
[question] run build without presets

### ISSUE THREAD

**Issue by esaulenka** [lukka/run-cmake#94]
I cannot find a way to run `cmake --build` without any `buildPresets`.

To be clear: I am using CMake with `make` generator and with a list of `configurePresets`. 
But I didn't find any useful settings in `buildPreset`, so I don't want to duplicate all items from config section to build in a `CMakePresets.json`.

I have two options: specify `buildPreset` key in action (it will cause build error) or skip it (then action just skip building). I don't like both alternatives ;)

Yes, as a workaround, I can specify something like `run: cmake .. --preset ${{preset}} && cmake --build .`, but it's not so elegant as dedicated solution.

**Comment by lukka** [comment]
@esaulenka if I get you right, you want to run `cmake --preset <name>` and then `cmake --build <something>`, without `--preset`.

You should be able to do it by customizing the [build command](https://github.com/lukka/run-cmake/blob/main/action.yml#L19) by defining what you want in the `buildPresetCmdString` input defined here: https://github.com/lukka/run-cmake/blob/main/action.yml#L41

```
buildPresetCmdString:
    default: "[`--build`, `--preset`, `$[env.BUILD_PRESET_NAME]`]"
    required: false
    description: "The CMake command format string to run the build." 
```

You may use:
```
uses: run-cmake
with:
  buildPresetCmdString: ['--build', 'something']
```

Assuming this is helpful, let me know how to improve the documentation so that this feature is more approachable by the users!
